/* Auto-generated by cbindgen - DO NOT EDIT MANUALLY */
/* BitNet FFI - C API for BitNet.rs */

#ifndef BITNET_FFI_H
#define BITNET_FFI_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define BITNET_FFI_API_VERSION 1

#ifdef BITNET_FFI_ENABLED

typedef struct bitnet_context_t bitnet_context_t;

typedef struct {
    uint32_t batch_size;
    uint32_t max_seq_len;
    float temperature;
    uint32_t top_k;
    float top_p;
    int32_t device_id;
    uint8_t use_cuda;
} bitnet_config_t;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Create a new BitNet context with the given configuration
 */
struct bitnet_context_t *bitnet_create_context(const struct bitnet_config_t *config);

/**
 * Destroy a BitNet context and free all associated resources
 */
void bitnet_destroy_context(struct bitnet_context_t *ctx);

/**
 * Generate text from a prompt
 * Returns 0 on success, negative error code on failure
 */
int32_t bitnet_generate(struct bitnet_context_t *ctx,
                        const char *prompt,
                        char *output,
                        size_t output_len);

/**
 * Get the last error message
 * Returns NULL if no error
 */
const char *bitnet_get_last_error(void);

/**
 * Load a model from file
 * Returns 0 on success, negative error code on failure
 */
int32_t bitnet_load_model(struct bitnet_context_t *ctx, const char *path);

/**
 * Get the version string
 */
const char *bitnet_version(void);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus

#endif // BITNET_FFI_ENABLED

#endif /* BITNET_FFI_H */