//! Low-level FFI bindings to BitNet C++ implementation
//!
//! This crate provides unsafe FFI bindings to the BitNet C++ implementation
//! for cross-validation purposes. It is only available when the `ffi`
//! feature is enabled (`crossval` is a deprecated alias).
//!
//! # Safety
//!
//! All functions in this crate are unsafe and require careful memory management.
//! Use the higher-level bindings in the `bitnet-crossval` crate instead.
//!
//! # Features
//!
//! - `ffi`: Enables FFI bindings (requires C++ dependencies)
//! - `crossval`: Backwards compatibility alias for `ffi`

#![cfg_attr(docsrs, feature(doc_cfg))]

pub mod symbol_analysis;
pub use symbol_analysis::CompileTimeLibCapabilities;

#[cfg(feature = "ffi")]
#[cfg_attr(docsrs, doc(cfg(feature = "ffi")))]
pub mod bindings {
    //! Raw FFI bindings generated by bindgen
    //!
    //! These bindings are automatically generated from the BitNet C++ headers
    //! and provide direct access to the C++ implementation.

    #![allow(non_upper_case_globals)]
    #![allow(non_camel_case_types)]
    #![allow(non_snake_case)]
    #![allow(dead_code)]
    #![allow(clippy::all)]

    // Include the generated bindings
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}

// wrapper and safe require real C++ symbols — skip in stub mode
#[cfg(all(feature = "ffi", not(bitnet_sys_stub)))]
#[cfg_attr(docsrs, doc(cfg(feature = "ffi")))]
pub mod wrapper;

#[cfg(all(feature = "ffi", not(bitnet_sys_stub)))]
#[cfg_attr(docsrs, doc(cfg(feature = "ffi")))]
pub mod safe {
    //! Safe wrappers around the raw FFI bindings
    //!
    //! This module provides safer abstractions over the raw C++ bindings
    //! with proper error handling and memory management.

    use crate::wrapper;
    use std::ops::{Deref, DerefMut};
    use std::panic;

    /// Error types for FFI operations
    #[derive(Debug, thiserror::Error)]
    pub enum SysError {
        #[error("Null pointer returned from C++")]
        NullPointer,

        #[error("Wrapper error: {0}")]
        Wrapper(#[from] wrapper::CppError),

        #[error("Invalid parameter: {0}")]
        InvalidParameter(String),
    }

    pub type Result<T> = std::result::Result<T, SysError>;

    /// Check if the C++ implementation is available by calling into the
    /// underlying library. If the symbols are missing or the call panics,
    /// this will return `false`.
    pub fn is_available() -> bool {
        panic::catch_unwind(|| {
            // Try calling a simple function to ensure the library is linked.
            wrapper::get_version();
        })
        .is_ok()
    }

    /// Get version information from the C++ implementation
    pub fn version() -> Result<String> {
        Ok(wrapper::get_version())
    }

    /// Initialize the C++ library
    pub fn initialize() -> Result<()> {
        wrapper::init_backend();
        Ok(())
    }

    /// Cleanup the C++ library
    pub fn cleanup() -> Result<()> {
        wrapper::free_backend();
        Ok(())
    }

    /// Handle for a loaded model/session
    pub struct ModelHandle(wrapper::Session);

    impl Deref for ModelHandle {
        type Target = wrapper::Session;
        fn deref(&self) -> &Self::Target {
            &self.0
        }
    }

    impl DerefMut for ModelHandle {
        fn deref_mut(&mut self) -> &mut Self::Target {
            &mut self.0
        }
    }

    /// Load a model from file using deterministic settings
    pub fn load_model(path: &str) -> Result<ModelHandle> {
        let session = wrapper::Session::load_deterministic(path)?;
        Ok(ModelHandle(session))
    }

    /// Generate up to `max_tokens` tokens and return their IDs
    /// (excluding the prompt).
    pub fn generate(model: &mut ModelHandle, prompt: &str, max_tokens: usize) -> Result<Vec<u32>> {
        if max_tokens == 0 {
            return Err(SysError::InvalidParameter("max_tokens must be > 0".to_string()));
        }

        let tokens = model.generate_greedy(prompt, max_tokens)?;
        Ok(tokens.into_iter().map(|t| t as u32).collect())
    }
}

// Disabled stubs used when: (a) ffi feature is not enabled, or
// (b) ffi is enabled but no C++ directory was found (stub mode).
#[cfg(any(not(feature = "ffi"), bitnet_sys_stub))]
pub mod disabled {
    //! Stub implementations when ffi is disabled or C++ libraries are unavailable.
    //!
    //! In stub mode (`BITNET_CPP_DIR` not set with `ffi` feature), all calls
    //! return errors at runtime while compilation succeeds.

    /// Error returned when ffi feature is disabled
    #[derive(Debug, thiserror::Error)]
    #[error(
        "BitNet C++ bindings not available (enable bitnet-sys/ffi with a populated BITNET_CPP_DIR or run setup-cpp-auto)"
    )]
    pub struct DisabledError;

    /// Check if C++ implementation is available (always false without ffi)
    pub fn is_available() -> bool {
        false
    }

    /// Get version (returns error without ffi)
    pub fn version() -> Result<String, DisabledError> {
        Err(DisabledError)
    }

    /// Get version information using the wrapper-compatible API.
    pub fn get_version() -> String {
        "unavailable".to_string()
    }

    /// Initialize the backend using the wrapper-compatible API.
    pub fn init_backend() {}

    /// Free the backend using the wrapper-compatible API.
    pub fn free_backend() {}

    /// Initialize (returns error without ffi)
    pub fn initialize() -> Result<(), DisabledError> {
        Err(DisabledError)
    }

    /// Placeholder model handle when ffi feature is disabled
    pub struct ModelHandle;

    /// Placeholder llama model when ffi feature is disabled or C++ is unavailable.
    pub struct Model;

    impl Model {
        /// Load a model from file.
        pub fn load(_path: &str) -> Result<Self, DisabledError> {
            Err(DisabledError)
        }

        /// Get the model vocabulary size.
        pub fn n_vocab(&self) -> i32 {
            0
        }

        /// Get the model training context size.
        pub fn n_ctx_train(&self) -> i32 {
            0
        }

        /// Get the model embedding dimension.
        pub fn n_embd(&self) -> i32 {
            0
        }
    }

    /// Placeholder llama context when ffi feature is disabled or C++ is unavailable.
    pub struct Context;

    impl Context {
        /// Create a context from a model.
        pub fn new(
            _model: &Model,
            _n_ctx: u32,
            _n_batch: u32,
            _n_threads: i32,
        ) -> Result<Self, DisabledError> {
            Err(DisabledError)
        }

        /// Tokenize text into token IDs.
        pub fn tokenize(&self, _text: &str, _add_special: bool) -> Result<Vec<i32>, DisabledError> {
            Err(DisabledError)
        }

        /// Tokenize text into token IDs with explicit special-token parsing.
        pub fn tokenize_with_options(
            &self,
            _text: &str,
            _add_special: bool,
            _parse_special: bool,
        ) -> Result<Vec<i32>, DisabledError> {
            Err(DisabledError)
        }

        /// Decode token IDs to text.
        pub fn decode(&self, _tokens: &[i32]) -> Result<String, DisabledError> {
            Err(DisabledError)
        }

        /// Evaluate tokens.
        pub fn eval(&mut self, _tokens: &[i32], _n_past: i32) -> Result<(), DisabledError> {
            Err(DisabledError)
        }

        /// Get logits from the last evaluation.
        pub fn get_logits(&self) -> Result<Vec<f32>, DisabledError> {
            Err(DisabledError)
        }

        /// Get logits for a token index.
        pub fn get_logits_ith(&self, _i: i32) -> Result<Vec<f32>, DisabledError> {
            Err(DisabledError)
        }

        /// Get logits for all token positions.
        pub fn get_all_logits(&self, _n_tokens: usize) -> Result<Vec<Vec<f32>>, DisabledError> {
            Err(DisabledError)
        }

        /// Sample greedily from logits.
        pub fn sample_greedy(&self, _logits: &[f32]) -> i32 {
            0
        }
    }

    /// Placeholder deterministic session when ffi feature is disabled or C++ is unavailable.
    pub struct Session {
        pub model: Model,
        pub context: Context,
    }

    impl Session {
        /// Load a model and create a context.
        pub fn load(
            _model_path: &str,
            _n_ctx: u32,
            _n_batch: u32,
            _n_threads: i32,
        ) -> Result<Self, DisabledError> {
            Err(DisabledError)
        }

        /// Load with deterministic settings.
        pub fn load_deterministic(_model_path: &str) -> Result<Self, DisabledError> {
            Err(DisabledError)
        }

        /// Tokenize text.
        pub fn tokenize(&self, _text: &str) -> Result<Vec<i32>, DisabledError> {
            Err(DisabledError)
        }

        /// Tokenize text with explicit BOS and special-token parsing policy.
        pub fn tokenize_with_options(
            &self,
            _text: &str,
            _add_special: bool,
            _parse_special: bool,
        ) -> Result<Vec<i32>, DisabledError> {
            Err(DisabledError)
        }

        /// Decode tokens to text.
        pub fn decode(&self, _tokens: &[i32]) -> Result<String, DisabledError> {
            Err(DisabledError)
        }

        /// Evaluate tokens and return logits.
        pub fn eval_and_get_logits(
            &mut self,
            _tokens: &[i32],
            _n_past: i32,
        ) -> Result<Vec<f32>, DisabledError> {
            Err(DisabledError)
        }

        /// Generate tokens greedily.
        pub fn generate_greedy(
            &mut self,
            _prompt: &str,
            _max_tokens: usize,
        ) -> Result<Vec<i32>, DisabledError> {
            Err(DisabledError)
        }
    }

    /// Placeholder BitNet model from the custom C shim.
    pub struct BitnetModel;

    impl BitnetModel {
        /// Load a model from file.
        pub fn from_file(_path: &str) -> Result<Self, DisabledError> {
            Err(DisabledError)
        }
    }

    /// Placeholder BitNet context from the custom C shim.
    pub struct BitnetContext;

    impl BitnetContext {
        /// Create a context from a BitNet model.
        pub fn new(
            _model: &BitnetModel,
            _n_ctx: i32,
            _n_threads: i32,
            _seed: i32,
        ) -> Result<Self, DisabledError> {
            Err(DisabledError)
        }
    }

    /// Tokenize text through the custom C shim.
    pub fn bitnet_tokenize_text(
        _model: &BitnetModel,
        _text: &str,
        _add_bos: bool,
        _parse_special: bool,
    ) -> Result<Vec<i32>, DisabledError> {
        Err(DisabledError)
    }

    /// Evaluate tokens through the custom C shim.
    pub fn bitnet_eval_tokens(
        _ctx: &BitnetContext,
        _ids: &[i32],
        _vocab_size: usize,
    ) -> Result<Vec<f32>, DisabledError> {
        Err(DisabledError)
    }

    /// Prefill a BitNet C shim context.
    pub fn bitnet_prefill(_ctx: &BitnetContext, _ids: &[i32]) -> Result<(), DisabledError> {
        Err(DisabledError)
    }

    /// Read the vocabulary size from a BitNet C shim context.
    pub fn cpp_vocab_size(_ctx: &BitnetContext) -> Result<usize, DisabledError> {
        Err(DisabledError)
    }

    /// Decode greedily through the custom C shim.
    pub fn cpp_decode_greedy(
        _model: &BitnetModel,
        _ctx: &BitnetContext,
        _eos_id: i32,
        _eot_id: Option<i32>,
        _max_steps: usize,
        _out: &mut [i32],
    ) -> Result<usize, DisabledError> {
        Err(DisabledError)
    }

    /// Load model (returns error without ffi)
    pub fn load_model(_path: &str) -> Result<ModelHandle, DisabledError> {
        Err(DisabledError)
    }

    /// Generate tokens (returns error without ffi)
    pub fn generate(
        _model: &mut ModelHandle,
        _prompt: &str,
        _max_tokens: usize,
    ) -> Result<Vec<u32>, DisabledError> {
        Err(DisabledError)
    }

    /// Cleanup (returns error without ffi)
    pub fn cleanup() -> Result<(), DisabledError> {
        Err(DisabledError)
    }
}

// Re-export the appropriate module based on feature
#[cfg(all(feature = "ffi", not(bitnet_sys_stub)))]
pub use safe::{
    ModelHandle, SysError, cleanup, generate, initialize, is_available, load_model, version,
};

#[cfg(all(feature = "ffi", not(bitnet_sys_stub)))]
pub use wrapper::{
    BitnetContext, BitnetModel, Context, CppError, Model, Session, bitnet_eval_tokens,
    bitnet_prefill, bitnet_tokenize_text, cpp_decode_greedy, cpp_vocab_size, free_backend,
    get_version, init_backend,
};

// Export Result types under different names to avoid conflicts
#[cfg(all(feature = "ffi", not(bitnet_sys_stub)))]
pub use safe::Result as SafeResult;

#[cfg(all(feature = "ffi", not(bitnet_sys_stub)))]
pub use wrapper::Result as WrapperResult;

// Use disabled stubs when ffi is off or C++ libs are unavailable (stub mode)
#[cfg(any(not(feature = "ffi"), bitnet_sys_stub))]
pub use disabled::*;
