//! Low-level FFI bindings to BitNet C++ implementation
//!
//! This crate provides unsafe FFI bindings to the BitNet C++ implementation
//! for cross-validation purposes. It is only available when the `ffi`
//! feature is enabled (`crossval` is a deprecated alias).
//!
//! # Safety
//!
//! All functions in this crate are unsafe and require careful memory management.
//! Use the higher-level bindings in the `bitnet-crossval` crate instead.
//!
//! # Features
//!
//! - `ffi`: Enables FFI bindings (requires C++ dependencies)
//! - `crossval`: Backwards compatibility alias for `ffi`

#![cfg_attr(docsrs, feature(doc_cfg))]

#[cfg(feature = "ffi")]
#[cfg_attr(docsrs, doc(cfg(feature = "ffi")))]
pub mod bindings {
    //! Raw FFI bindings generated by bindgen
    //!
    //! These bindings are automatically generated from the BitNet C++ headers
    //! and provide direct access to the C++ implementation.

    #![allow(non_upper_case_globals)]
    #![allow(non_camel_case_types)]
    #![allow(non_snake_case)]
    #![allow(dead_code)]
    #![allow(clippy::all)]

    // Include the generated bindings
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}

#[cfg(feature = "ffi")]
#[cfg_attr(docsrs, doc(cfg(feature = "ffi")))]
pub mod wrapper;

#[cfg(feature = "ffi")]
#[cfg_attr(docsrs, doc(cfg(feature = "ffi")))]
pub mod safe {
    //! Safe wrappers around the raw FFI bindings
    //!
    //! This module provides safer abstractions over the raw C++ bindings
    //! with proper error handling and memory management.

    use crate::wrapper;
    use std::ops::{Deref, DerefMut};
    use std::panic;

    /// Error types for FFI operations
    #[derive(Debug, thiserror::Error)]
    pub enum SysError {
        #[error("Null pointer returned from C++")]
        NullPointer,

        #[error("Wrapper error: {0}")]
        Wrapper(#[from] wrapper::CppError),

        #[error("Invalid parameter: {0}")]
        InvalidParameter(String),
    }

    pub type Result<T> = std::result::Result<T, SysError>;

    /// Check if the C++ implementation is available by calling into the
    /// underlying library. If the symbols are missing or the call panics,
    /// this will return `false`.
    pub fn is_available() -> bool {
        panic::catch_unwind(|| {
            // Try calling a simple function to ensure the library is linked.
            wrapper::get_version();
        })
        .is_ok()
    }

    /// Get version information from the C++ implementation
    pub fn version() -> Result<String> {
        Ok(wrapper::get_version())
    }

    /// Initialize the C++ library
    pub fn initialize() -> Result<()> {
        wrapper::init_backend();
        Ok(())
    }

    /// Cleanup the C++ library
    pub fn cleanup() -> Result<()> {
        wrapper::free_backend();
        Ok(())
    }

    /// Handle for a loaded model/session
    pub struct ModelHandle(wrapper::Session);

    impl Deref for ModelHandle {
        type Target = wrapper::Session;
        fn deref(&self) -> &Self::Target {
            &self.0
        }
    }

    impl DerefMut for ModelHandle {
        fn deref_mut(&mut self) -> &mut Self::Target {
            &mut self.0
        }
    }

    /// Load a model from file using deterministic settings
    pub fn load_model(path: &str) -> Result<ModelHandle> {
        let session = wrapper::Session::load_deterministic(path)?;
        Ok(ModelHandle(session))
    }

    /// Generate up to `max_tokens` tokens and return their IDs
    /// (excluding the prompt).
    pub fn generate(model: &mut ModelHandle, prompt: &str, max_tokens: usize) -> Result<Vec<u32>> {
        if max_tokens == 0 {
            return Err(SysError::InvalidParameter("max_tokens must be > 0".to_string()));
        }

        let tokens = model.generate_greedy(prompt, max_tokens)?;
        Ok(tokens.into_iter().map(|t| t as u32).collect())
    }
}

#[cfg(not(feature = "ffi"))]
pub mod disabled {
    //! Disabled stubs when ffi feature is not enabled
    //!
    //! This module provides stub implementations that return errors
    //! when the ffi feature is not enabled.

    /// Error returned when ffi feature is disabled
    #[derive(Debug, thiserror::Error)]
    #[error("BitNet C++ bindings not available (compile with --features bitnet-sys/ffi)")]
    pub struct DisabledError;

    /// Check if C++ implementation is available (always false without ffi)
    pub fn is_available() -> bool {
        false
    }

    /// Get version (returns error without ffi)
    pub fn version() -> Result<String, DisabledError> {
        Err(DisabledError)
    }

    /// Initialize (returns error without ffi)
    pub fn initialize() -> Result<(), DisabledError> {
        Err(DisabledError)
    }

    /// Placeholder model handle when ffi feature is disabled
    pub struct ModelHandle;

    /// Load model (returns error without ffi)
    pub fn load_model(_path: &str) -> Result<ModelHandle, DisabledError> {
        Err(DisabledError)
    }

    /// Generate tokens (returns error without ffi)
    pub fn generate(
        _model: &mut ModelHandle,
        _prompt: &str,
        _max_tokens: usize,
    ) -> Result<Vec<u32>, DisabledError> {
        Err(DisabledError)
    }

    /// Cleanup (returns error without ffi)
    pub fn cleanup() -> Result<(), DisabledError> {
        Err(DisabledError)
    }
}

// Re-export the appropriate module based on feature
#[cfg(feature = "ffi")]
pub use safe::{
    ModelHandle, SysError, cleanup, generate, initialize, is_available, load_model, version,
};

#[cfg(feature = "ffi")]
pub use wrapper::{
    BitnetContext, BitnetModel, Context, CppError, Model, Session, bitnet_eval_tokens,
    bitnet_prefill, bitnet_tokenize_text, cpp_decode_greedy, cpp_vocab_size, free_backend,
    get_version, init_backend,
};

// Export Result types under different names to avoid conflicts
#[cfg(feature = "ffi")]
pub use safe::Result as SafeResult;

#[cfg(feature = "ffi")]
pub use wrapper::Result as WrapperResult;

#[cfg(not(feature = "ffi"))]
pub use disabled::*;
