//! Low-level FFI bindings to BitNet C++ implementation
//!
//! This crate provides unsafe FFI bindings to the BitNet C++ implementation
//! for cross-validation purposes. It is only available when the `crossval`
//! feature is enabled.
//!
//! # Safety
//!
//! All functions in this crate are unsafe and require careful memory management.
//! Use the higher-level bindings in the `bitnet-crossval` crate instead.
//!
//! # Features
//!
//! - `crossval`: Enables FFI bindings (requires C++ dependencies)

#![cfg_attr(docsrs, feature(doc_cfg))]

#[cfg(feature = "ffi")]
#[cfg_attr(docsrs, doc(cfg(feature = "ffi")))]
pub mod bindings {
    //! Raw FFI bindings generated by bindgen
    //!
    //! These bindings are automatically generated from the BitNet C++ headers
    //! and provide direct access to the C++ implementation.

    #![allow(non_upper_case_globals)]
    #![allow(non_camel_case_types)]
    #![allow(non_snake_case)]
    #![allow(dead_code)]
    #![allow(clippy::all)]

    // Include the generated bindings
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}

#[cfg(feature = "ffi")]
#[cfg_attr(docsrs, doc(cfg(feature = "ffi")))]
pub mod wrapper;

#[cfg(feature = "ffi")]
#[cfg_attr(docsrs, doc(cfg(feature = "ffi")))]
pub mod safe {
    //! Safe wrappers around the raw FFI bindings
    //!
    //! This module provides safer abstractions over the raw C++ bindings
    //! with proper error handling and memory management.

    use std::ffi::{CStr, CString};
    use std::os::raw::{c_char, c_int, c_void};
    use std::ptr;

    /// Error types for FFI operations
    #[derive(Debug, thiserror::Error)]
    pub enum SysError {
        #[error("Null pointer returned from C++")]
        NullPointer,
        
        #[error("Invalid string encoding: {0}")]
        InvalidString(#[from] std::ffi::NulError),
        
        #[error("C++ function returned error code: {0}")]
        CppError(i32),
        
        #[error("Invalid parameter: {0}")]
        InvalidParameter(String),
    }

    pub type Result<T> = std::result::Result<T, SysError>;

    /// Check if the C++ implementation is available
    pub fn is_available() -> bool {
        // This will be true only when compiled with crossval feature
        // and C++ library is successfully linked
        true
    }

    /// Get version information from the C++ implementation
    pub fn version() -> Result<String> {
        // Placeholder implementation
        // In real code, this would call into C++ to get version info
        Ok("BitNet.cpp (external)".to_string())
    }

    /// Initialize the C++ library
    pub fn initialize() -> Result<()> {
        // Placeholder for C++ library initialization
        // In real code, this might call bitnet_cpp_init() or similar
        Ok(())
    }

    /// Cleanup the C++ library
    pub fn cleanup() -> Result<()> {
        // Placeholder for C++ library cleanup
        // In real code, this might call bitnet_cpp_cleanup() or similar
        Ok(())
    }

    /// Raw model handle from C++
    #[repr(transparent)]
    pub struct ModelHandle(*mut c_void);

    impl ModelHandle {
        /// Create a new model handle from a raw pointer
        /// 
        /// # Safety
        /// 
        /// The pointer must be valid and point to a valid C++ model object
        pub unsafe fn from_raw(ptr: *mut c_void) -> Option<Self> {
            if ptr.is_null() {
                None
            } else {
                Some(ModelHandle(ptr))
            }
        }

        /// Get the raw pointer
        /// 
        /// # Safety
        /// 
        /// The returned pointer is only valid as long as this handle exists
        pub unsafe fn as_raw(&self) -> *mut c_void {
            self.0
        }
    }

    // Safety: ModelHandle is only used in single-threaded cross-validation contexts
    unsafe impl Send for ModelHandle {}

    impl Drop for ModelHandle {
        fn drop(&mut self) {
            // In real implementation, this would call the C++ destructor
            // For now, just mark as dropped
            self.0 = ptr::null_mut();
        }
    }

    /// Load a model from file
    pub fn load_model(path: &str) -> Result<ModelHandle> {
        let c_path = CString::new(path)?;
        
        // Placeholder implementation
        // In real code, this would call bitnet_cpp_load_model(c_path.as_ptr())
        let raw_ptr = ptr::null_mut(); // Placeholder
        
        unsafe {
            ModelHandle::from_raw(raw_ptr)
                .ok_or(SysError::NullPointer)
        }
    }

    /// Generate tokens using a loaded model
    pub fn generate(
        model: &ModelHandle,
        prompt: &str,
        max_tokens: usize,
    ) -> Result<Vec<u32>> {
        let c_prompt = CString::new(prompt)?;
        
        if max_tokens == 0 {
            return Err(SysError::InvalidParameter("max_tokens must be > 0".to_string()));
        }
        
        let mut tokens = vec![0u32; max_tokens];
        let mut actual_count: c_int = 0;
        
        // Placeholder implementation
        // In real code, this would call:
        // let result = bitnet_cpp_generate(
        //     model.as_raw(),
        //     c_prompt.as_ptr(),
        //     max_tokens as c_int,
        //     tokens.as_mut_ptr(),
        //     &mut actual_count,
        // );
        
        let result = 0; // Placeholder success
        
        if result != 0 {
            return Err(SysError::CppError(result));
        }
        
        if actual_count < 0 {
            return Err(SysError::InvalidParameter("Invalid token count".to_string()));
        }
        
        tokens.truncate(actual_count as usize);
        Ok(tokens)
    }
}

#[cfg(not(feature = "ffi"))]
pub mod disabled {
    //! Disabled stubs when ffi feature is not enabled
    //!
    //! This module provides stub implementations that return errors
    //! when the ffi feature is not enabled.

    /// Error returned when ffi feature is disabled
    #[derive(Debug, thiserror::Error)]
    #[error("BitNet C++ bindings not available (compile with --features bitnet-sys/ffi)")]
    pub struct DisabledError;

    /// Check if C++ implementation is available (always false without ffi)
    pub fn is_available() -> bool {
        false
    }

    /// Get version (returns error without ffi)
    pub fn version() -> Result<String, DisabledError> {
        Err(DisabledError)
    }

    /// Initialize (returns error without ffi)
    pub fn initialize() -> Result<(), DisabledError> {
        Err(DisabledError)
    }

    /// Load model (returns error without ffi)
    pub fn load_model(_path: &str) -> Result<(), DisabledError> {
        Err(DisabledError)
    }
}

// Re-export the appropriate module based on feature
#[cfg(feature = "ffi")]
pub use safe::*;

#[cfg(feature = "ffi")]
pub use wrapper::*;

#[cfg(not(feature = "ffi"))]
pub use disabled::*;