/* BitNet FFI C API - Auto-generated header
 * ABI Version: 1
 * Do not modify this file manually
 */

#ifndef BITNET_FFI_H
#define BITNET_FFI_H

#ifdef __cplusplus
extern "C" {
#endif

#ifndef BITNET_FFI_H
#define BITNET_FFI_H

/* WARNING: This file is auto-generated by cbindgen. Do not modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * ABI version for compatibility checking
 */
#define BITNET_ABI_VERSION 1

/**
 * Error codes matching existing C++ API
 */
#define BITNET_SUCCESS 0

#define BITNET_ERROR_INVALID_ARGUMENT -1

#define BITNET_ERROR_MODEL_NOT_FOUND -2

#define BITNET_ERROR_MODEL_LOAD_FAILED -3

#define BITNET_ERROR_INFERENCE_FAILED -4

#define BITNET_ERROR_OUT_OF_MEMORY -5

#define BITNET_ERROR_THREAD_SAFETY -6

#define BITNET_ERROR_INVALID_MODEL_ID -7

#define BITNET_ERROR_CONTEXT_LENGTH_EXCEEDED -8

#define BITNET_ERROR_UNSUPPORTED_OPERATION -9

#define BITNET_ERROR_INTERNAL -10

#endif  /* BITNET_FFI_H */

#ifdef __cplusplus
}
#endif

#endif /* BITNET_FFI_H */
