//! Core build metadata derived from compile-time environment variables.

use serde::{Deserialize, Serialize};

/// Canonical build metadata shared across crates.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct BuildInfo {
    pub version: String,
    pub git_sha: String,
    pub git_branch: String,
    pub build_timestamp: String,
    pub rustc_version: String,
    pub cargo_target: String,
    pub cargo_profile: String,
}

/// Git SHA generated by `vergen`.
pub const GIT_SHA: &str = match option_env!("VERGEN_GIT_SHA") {
    Some(value) => value,
    None => "unknown",
};
/// Git branch generated by `vergen`.
pub const GIT_BRANCH: &str = match option_env!("VERGEN_GIT_BRANCH") {
    Some(value) => value,
    None => "unknown",
};
/// Build timestamp generated by `vergen`.
pub const BUILD_TIMESTAMP: &str = match option_env!("VERGEN_BUILD_TIMESTAMP") {
    Some(value) => value,
    None => "unknown",
};
/// Rust compiler semver generated by `vergen`.
pub const RUSTC_VERSION: &str = match option_env!("VERGEN_RUSTC_SEMVER") {
    Some(value) => value,
    None => "unknown",
};
/// Cargo target triple generated by `vergen`.
pub const CARGO_TARGET_TRIPLE: &str = match option_env!("VERGEN_CARGO_TARGET_TRIPLE") {
    Some(value) => value,
    None => "unknown",
};
/// Cargo optimization level generated by `vergen`.
pub const CARGO_OPT_LEVEL: &str = match option_env!("VERGEN_CARGO_OPT_LEVEL") {
    Some(value) => value,
    None => "unknown",
};

/// Convert a compile-time environment variable into a display-safe string.
#[must_use]
pub fn env_to_string(value: Option<&'static str>) -> String {
    value.unwrap_or("unknown").to_string()
}

/// Build metadata from vergen-generated environment variables.
#[must_use]
pub fn collect(version: &str) -> BuildInfo {
    BuildInfo {
        version: version.to_string(),
        git_sha: env_to_string(option_env!("VERGEN_GIT_SHA")),
        git_branch: env_to_string(option_env!("VERGEN_GIT_BRANCH")),
        build_timestamp: env_to_string(option_env!("VERGEN_BUILD_TIMESTAMP")),
        rustc_version: env_to_string(option_env!("VERGEN_RUSTC_SEMVER")),
        cargo_target: env_to_string(option_env!("VERGEN_CARGO_TARGET_TRIPLE")),
        cargo_profile: env_to_string(option_env!("VERGEN_CARGO_OPT_LEVEL")),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn env_to_string_defaults_unknown() {
        assert_eq!(env_to_string(None), "unknown");
    }

    #[test]
    fn env_to_string_keeps_value() {
        assert_eq!(env_to_string(Some("abc")), "abc");
    }

    #[test]
    fn collect_uses_supplied_version() {
        let info = collect("1.2.3");
        assert_eq!(info.version, "1.2.3");
    }
}
