[package]
name = "bitnet-task"
version.workspace = true
edition.workspace = true
publish = false
license.workspace = true

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
fs2 = "0.4.3"
serde_json.workspace = true
sha2 = "0.10.9"
tempfile.workspace = true

[lints]
workspace = true
