[package]
name = "bitnet-task"
version.workspace = true
edition.workspace = true
publish = false
license.workspace = true

[dependencies]
bitnet-greedy-argmax-core = { path = "../../crates/bitnet-greedy-argmax-core", version = "0.2.1-dev" }
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
fs2 = "0.4.3"
serde_json.workspace = true
sha2 = "0.10.9"
tempfile.workspace = true

[lints]
workspace = true
