//! Tests verifying receipt schema invariants.
//!
//! Focused on the four core guarantees:
//! 1. Schema version constant == "1.0.0"
//! 2. `compute_path` is "real" (distinct from "mock")
//! 3. Kernel ID hygiene: non-empty, length ≤ 128
//! 4. Selected backend is recorded in the receipt

use bitnet_receipts::{InferenceReceipt, RECEIPT_SCHEMA_VERSION};
use proptest::prelude::*;

// ── Unit tests ────────────────────────────────────────────────────────────────

#[test]
fn schema_version_constant_is_correct() {
    assert_eq!(RECEIPT_SCHEMA_VERSION, "1.0.0");
}

#[test]
fn compute_path_real_and_mock_are_distinct() {
    let real = "real";
    let mock = "mock";
    assert_ne!(real, mock);
    assert_eq!(real, "real");
}

/// `generate()` records the backend passed to it in the receipt's `backend` field.
#[test]
fn selected_backend_is_recorded_in_receipt() {
    let receipt = InferenceReceipt::generate("cpu", vec!["i2s_gemv".to_string()], None).unwrap();
    assert_eq!(receipt.backend, "cpu");
}

// ── Property tests ────────────────────────────────────────────────────────────

proptest! {
    /// Every kernel ID generated by the valid-ID regex is non-empty and within
    /// the 128-character limit.  This encodes the hygiene contract as a spec test.
    #[test]
    fn kernel_id_must_not_be_empty(
        kernel_ids in prop::collection::vec(
            prop::string::string_regex("[a-z_]{1,128}").unwrap(),
            0..10,
        )
    ) {
        for id in &kernel_ids {
            prop_assert!(!id.is_empty(), "kernel_id must not be empty");
            prop_assert!(id.len() <= 128, "kernel_id must be ≤ 128 chars, got {}", id.len());
        }
    }

    /// Any single valid kernel ID string is non-empty and within the 128-character limit.
    #[test]
    fn kernel_id_length_within_bounds(
        s in prop::string::string_regex("[a-z_]{1,128}").unwrap()
    ) {
        prop_assert!(!s.is_empty());
        prop_assert!(s.len() <= 128);
    }

    /// `validate_kernel_ids()` accepts receipts whose kernel IDs are all valid
    /// (non-empty, ≤ 128 chars, no mock prefix).
    #[test]
    fn valid_kernel_ids_accepted_by_validate(
        kernels in prop::collection::vec(
            prop::string::string_regex("[a-z][a-z0-9_]{0,30}").unwrap(),
            1..8,
        )
    ) {
        let kernels: Vec<String> = kernels
            .into_iter()
            .filter(|k| !k.is_empty() && k.len() <= 128 && !k.to_lowercase().contains("mock"))
            .collect();
        if kernels.is_empty() {
            return Ok(());
        }
        let receipt = InferenceReceipt::generate("cpu", kernels, None).unwrap();
        prop_assert!(receipt.validate_kernel_ids().is_ok());
    }

    /// A kernel ID whose length exceeds 128 characters causes `validate_kernel_ids()`
    /// to return an error.
    #[test]
    fn oversized_kernel_id_rejected_by_validate(extra in 1_usize..50) {
        let oversized = "k".repeat(128 + extra);
        let mut receipt =
            InferenceReceipt::generate("cpu", vec!["i2s_gemv".to_string()], None).unwrap();
        receipt.kernels = vec![oversized];
        prop_assert!(receipt.validate_kernel_ids().is_err());
    }
}

fn strict_cpu_decode_metadata() -> bitnet_receipts::StrictCpuDecodeMetadata {
    bitnet_receipts::StrictCpuDecodeMetadata {
        requested_backend: "cpu".to_string(),
        selected_backend: "cpu".to_string(),
        requested_kernel: "qk256-avx2-gemv".to_string(),
        selected_kernel: "qk256-avx2-gemv".to_string(),
        loader_mode: "real_gguf".to_string(),
        tokenizer_source: "explicit".to_string(),
        model_family: "bitnet".to_string(),
        quant_format: "qk256_i2_s".to_string(),
        cpu_features: vec!["avx2".to_string(), "fma".to_string()],
        thread_count: 8,
        fallback_used: false,
        fallback_reason: None,
        prompt_tokens: 512,
        decode_tokens: 128,
        p50_latency_ms: 4.0,
        p95_latency_ms: 8.0,
        decode_tokens_per_second: 125.0,
    }
}

fn strict_cpu_receipt() -> InferenceReceipt {
    InferenceReceipt::generate(
        "cpu",
        vec!["qk256-avx2-gemv".to_string(), "rope_apply".to_string()],
        Some("requested=cpu detected=[cpu] selected=cpu".to_string()),
    )
    .unwrap()
    .with_parity(bitnet_receipts::ParityMetadata {
        cpp_available: false,
        cosine_similarity: None,
        exact_match_rate: None,
        status: "rust_only".to_string(),
    })
    .with_strict_cpu_decode(strict_cpu_decode_metadata())
}

#[test]
fn strict_cpu_decode_receipt_validates_real_no_fallback_path() {
    let receipt = strict_cpu_receipt();
    assert!(receipt.validate().is_ok());
    assert!(receipt.validate_strict_cpu_decode().is_ok());
}

#[test]
fn strict_cpu_decode_rejects_loader_fallback() {
    let mut receipt = strict_cpu_receipt();
    receipt.strict_cpu_decode.as_mut().unwrap().loader_mode = "simple".to_string();
    let err = receipt.validate().unwrap_err().to_string();
    assert!(err.contains("loader_mode=real_gguf"), "{err}");
}

#[test]
fn strict_cpu_decode_rejects_tokenizer_fallback() {
    let mut receipt = strict_cpu_receipt();
    receipt.strict_cpu_decode.as_mut().unwrap().tokenizer_source = "gpt2_fallback".to_string();
    let err = receipt.validate().unwrap_err().to_string();
    assert!(err.contains("tokenizer_source"), "{err}");
}

#[test]
fn strict_cpu_decode_rejects_kernel_mismatch() {
    let mut receipt = strict_cpu_receipt();
    receipt.strict_cpu_decode.as_mut().unwrap().selected_kernel = "qk256-scalar-gemv".to_string();
    let err = receipt.validate().unwrap_err().to_string();
    assert!(err.contains("kernel mismatch"), "{err}");
}

#[test]
fn strict_cpu_decode_rejects_fallback_flag() {
    let mut receipt = strict_cpu_receipt();
    let strict = receipt.strict_cpu_decode.as_mut().unwrap();
    strict.fallback_used = true;
    strict.fallback_reason = Some("avx2 unavailable".to_string());
    let err = receipt.validate().unwrap_err().to_string();
    assert!(err.contains("fallback_used=true"), "{err}");
}
