#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
CRATES_FILE="$ROOT_DIR/tools/maintenance/public_api_crates.txt"
OUT_DIR="$ROOT_DIR/docs/public_api"
INDEX_FILE="$OUT_DIR/README.md"

if ! command -v cargo-public-api >/dev/null 2>&1; then
  echo "cargo-public-api is required. Install with: cargo install cargo-public-api --locked" >&2
  exit 1
fi

mkdir -p "$OUT_DIR"
{
  echo "# Public API Snapshots"
  echo
  echo "Generated by \\`scripts/maintenance/generate_public_api_snapshot.sh\\`."
  echo
} > "$INDEX_FILE"

while IFS= read -r crate; do
  [[ -z "$crate" ]] && continue
  out="$OUT_DIR/${crate}.txt"
  cargo public-api --manifest-path "$ROOT_DIR/Cargo.toml" -p "$crate" --simplified > "$out"
  count="$(wc -l < "$out" | tr -d ' ')"
  echo "- [${crate}](${crate}.txt) (${count} lines)" >> "$INDEX_FILE"
done < "$CRATES_FILE"

echo "Wrote snapshots to $OUT_DIR"
