#!/usr/bin/env python3
import json, subprocess
from pathlib import Path

root = Path(__file__).resolve().parents[2]
out_md = root / 'docs/deps.md'
out_json = root / 'docs/deps.json'

metadata = subprocess.check_output([
    'cargo','metadata','--format-version','1','--no-deps'
], cwd=root, text=True)
md = json.loads(metadata)
workspace_members = set(md['workspace_members'])
packages = {p['id']: p for p in md['packages']}
name_by_id = {pid: pkg['name'] for pid, pkg in packages.items()}

edges = set()
for pid in sorted(workspace_members):
    pkg = packages.get(pid)
    if not pkg:
        continue
    src = pkg['name']
    for dep in pkg.get('dependencies', []):
        dep_name = dep.get('name')
        if dep_name and dep_name.startswith('bitnet'):
            edges.add((src, dep_name))

nodes = sorted({a for a, _ in edges} | {b for _, b in edges})

lines = [
    '# Crate Dependency Graph',
    '',
    'Generated by `scripts/maintenance/generate_deps_graph.py`.',
    '',
    '```mermaid',
    'graph LR',
]
for a,b in sorted(edges):
    lines.append(f'  {a.replace("-","_")} --> {b.replace("-","_")}')
lines.append('```')
lines.append('')
lines.append(f'Total crates in graph: **{len(nodes)}**')
lines.append(f'Total edges in graph: **{len(edges)}**')
out_md.write_text('\n'.join(lines) + '\n')

out_json.write_text(json.dumps({
    'nodes': nodes,
    'edges': sorted([{'from': a, 'to': b} for a,b in edges], key=lambda x:(x['from'],x['to']))
}, indent=2) + '\n')
print(f'wrote {out_md} and {out_json}')
