#!/usr/bin/env python3
import re
from pathlib import Path

root = Path(__file__).resolve().parents[2]
out = root / 'docs/status.md'

cargo = (root/'Cargo.toml').read_text()
msrv = re.search(r'rust-version\s*=\s*"([0-9.]+)"', cargo)
msrv = msrv.group(1) if msrv else 'unknown'

workflows = sorted((root/'.github/workflows').glob('*.yml'))
specs = sorted((root/'docs/specs').glob('*.md')) if (root/'docs/specs').exists() else []

lines = [
    '# Repo Invariants Status',
    '',
    'Generated by `scripts/maintenance/generate_status_report.py`.',
    '',
    f'- **MSRV**: `{msrv}`',
    f'- **Workflow count**: `{len(workflows)}`',
    f'- **Spec documents**: `{len(specs)}`',
    '',
    '## CI Gate Set',
]
for wf in workflows:
    lines.append(f'- `{wf.name}`')

out.write_text('\n'.join(lines)+'\n')
print(f'wrote {out}')
