[package]
authors.workspace = true
categories.workspace = true
description = "SRP core primitives for API key authentication"
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
name = "bitnet-api-key-auth-core"
repository.workspace = true
version.workspace = true

[dependencies]
bitnet-http-auth-core = { path = "../bitnet-http-auth-core", version = "0.2.1-dev" }
