#!/usr/bin/env bash
# Tokenizer Test Fixture Generator
#
# **Purpose**: Generate test fixtures for TokenizerAuthority E2E tests
#
# **Specification**: docs/specs/tokenizer-authority-validation-tests.md#9
#
# **Fixtures Generated**:
#   - valid_tokenizer_a.json       # Reference tokenizer (128000 vocab)
#   - valid_tokenizer_b.json       # Byte-identical clone of A
#   - different_vocab_size.json    # Modified tokenizer with 64000 vocab
#   - corrupted.json               # Malformed JSON (error handling tests)
#   - README.md                    # Fixture documentation
#
# **Requirements**:
#   - Model downloaded: cargo run -p xtask -- download-model
#   - jq installed (for JSON manipulation)
#
# **Usage**:
#   ./scripts/generate_tokenizer_fixtures.sh

set -euo pipefail

FIXTURES_DIR="tests/fixtures/tokenizers"
MODELS_DIR="models/microsoft-bitnet-b1.58-2B-4T-gguf"

echo "==================================================================="
echo "Tokenizer Test Fixture Generator"
echo "==================================================================="
echo ""

SOURCE_TOKENIZER="$MODELS_DIR/tokenizer.json"

if [[ ! -f "$SOURCE_TOKENIZER" ]]; then
    echo "ERROR: Source tokenizer not found at: $SOURCE_TOKENIZER" >&2
    echo "" >&2
    echo "Download the test model assets first:" >&2
    echo "  cargo run -p xtask -- download-model" >&2
    exit 1
fi

mkdir -p "$FIXTURES_DIR"
echo "Created fixtures directory: $FIXTURES_DIR"

cp "$SOURCE_TOKENIZER" "$FIXTURES_DIR/valid_tokenizer_a.json"
echo "Generated: valid_tokenizer_a.json"

cp "$FIXTURES_DIR/valid_tokenizer_a.json" "$FIXTURES_DIR/valid_tokenizer_b.json"
echo "Generated: valid_tokenizer_b.json (byte-identical clone)"

if command -v jq >/dev/null 2>&1; then
    jq '.model.vocab |= .[:64000] | .model.scores |= .[:64000]' \
        "$FIXTURES_DIR/valid_tokenizer_a.json" \
        > "$FIXTURES_DIR/different_vocab_size.json"
    echo "Generated: different_vocab_size.json (truncated to 64000 vocab entries)"
else
    echo "WARNING: jq not found; skipping different_vocab_size.json generation" >&2
fi

head -c 500 "$FIXTURES_DIR/valid_tokenizer_a.json" > "$FIXTURES_DIR/corrupted.json"
echo "Generated: corrupted.json (intentionally truncated JSON)"

cat > "$FIXTURES_DIR/README.md" <<'EOF'
# Tokenizer test fixtures

Generated by `scripts/generate_tokenizer_fixtures.sh` for TokenizerAuthority E2E tests.

## Files

- `valid_tokenizer_a.json`: Reference tokenizer copied from downloaded model assets.
- `valid_tokenizer_b.json`: Byte-identical clone of `valid_tokenizer_a.json`.
- `different_vocab_size.json`: Variant with `.model.vocab` and `.model.scores` truncated to 64,000 entries (requires `jq`).
- `corrupted.json`: Intentionally malformed JSON created by truncating the reference tokenizer file.

## Regenerate

1. Ensure model assets are downloaded:
   - `cargo run -p xtask -- download-model`
2. Run:
   - `./scripts/generate_tokenizer_fixtures.sh`

## Usage

These fixtures are consumed by E2E tests in `xtask/tests/tokenizer_authority_e2e_tests.rs`.
EOF
echo "Generated: README.md"

fixture_count="$(find "$FIXTURES_DIR" -maxdepth 1 -type f | wc -l | tr -d ' ')"

echo ""
echo "==================================================================="
echo "Fixture generation complete ($fixture_count files)"
echo "Location: $FIXTURES_DIR"
ls -lh "$FIXTURES_DIR"
echo "==================================================================="
